ignore_merge_commits = false
branch_whitelist = ["main"]
pre_bump_hooks = []
post_bump_hooks = ["git push", "git push origin {{version}}"]

[commit_types]
hotfix = { changelog_title = "Hotfixes" }
release = { changelog_title = "Releases" }

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "goose-game"
owner = "sRavioli"
authors = [{ username = "sRavioli", signature = "Simone Fidanza" }]

# [bump_profiles]

# [packages]
